### ISSUE TITLE
Unresponsive buttons - Submit contact form, Add Upcoming Event, Magazine Save File Upload

### ISSUE THREAD

**Issue by andrewelawrence** [JumboCode/the-lantern#224]
Hi,

We did not test the website over the summer and returning to the deployed version now we have encountered issues with the following Buttons:
1. https://the-lantern.vercel.app/Events - Edit Upcoming Edits (+) button
2. https://the-lantern.vercel.app/Magazine - Edit Magazine > Upload new file > Save file upload button
3. https://the-lantern.vercel.app/ContactUs - Contact form is unresponsive.

We have not altered the AWS, Vercel, or MongoDB configs and so are unsure why these issues have appeared since the hand-off. (To be honest, I am not certain if we tested all the features during the hand-off and so it could be they linger from tests prior to prod.) 

Please let us know how you would like us to proceed.

Andrew
(The Lantern E-board tech lead)

**Comment by sristii** [comment]
resolved
